/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.so.agi.oereb.v2;

public class Main {

    public static void main(String[] args) {
        System.out.println("Hallo Welt.");
    }
}
